### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by icco** [impaler/bandcamp-dl#1]
```
Run error
Cannot read property 'dispatchEvent' of null
```

I assume this is just because the site has changed since you wrote this.

**Comment by wwboynton** [comment]
Came here to say the same, though I had (maybe mistakenly) suspected the script relied on behaviour not present when one has a combination fan/artist account, since it goes directly to your band page instead of logging in as it would for a fan-only account.

**Comment by icco** [comment]
Oh interesting... I too have a combo account...

**Comment by impaler** [comment]
@icco @wwboynton indeed it was broken some time ago from changes in the website. I wanted to use this myself again and have been working on a wip refactor here https://github.com/impaler/bandcamp-dl/tree/refactor let me know if you keen to test it or help, so far so good.
